---
title: "My resume"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---
# Academic and Professional Experience

## Education
**Columbia University**: MPH in epidemiology with a Certificate in Biostatistics 

Courses: Applied Regression, Research Methods & Application, Analysis of Categorical Data, Applied of Epi methods(SAS)

**New York University**: MS in Information Technology Project Management GPA:3.9 

Courses: Management of Information Systems, Applying PM in IT, Agile PM, Enterprise Project Management

**Sichuan University**: Bachelor of Engineering in Electrical Engineering, Minor in public health and finance June,2021, CN

Courses: Calculus, Statistics, Numerical Computation Methods, Electromagnetic Fields, Introduction to Pharmaceutical Engineering, Introduction to Public Health and Medicine, Accounting, Economics, Banking and Financial Market

## Professional Experience

**Daiwa Securities Group: Analyst Intern July-Sep 2022, Beijing, CN**

- Conducted desktop research on China’s hospice care and dentistry care to support the team’s investment decision.
- Composed a case analysis on Japan’s hospice care industry as a leading example to benchmark the respective market growth potential in China; focused on the impact of public policy and digitized medical service trends on the enterprise-based pension
system in Japan and China. Visualized insights with Power BI for senior leadership to review.

**PricewaterhouseCoopers: Analyst Intern Infrastructure & Capital Projects March-Sep 2021 Beijing, CN**

- Participated in the Smart City Transformation Project for the government of Wenchang, Hainan, with a focus on healthcare resource distribution; performed comparative analysis over five existing smart city cases globally to provide strategic advice and benchmark to measure success, focused on incorporating artificial intelligence and cloud computing to improve healthcare resource distribution; visualized findings with Power BI and presented to city officials.

- Collaborated with the World Bank to set a foundation for an economic promotional project for port cities in Africa; conducted desk research on relevant policy and regulation, qualitative interviews with scholars, and financial analysis to construct the framework,
performed comparative analysis over best practices.

**JP Morgan: Part Time Assistant January – March 2021, Remote CN**

- Assist with DCF model and financial analysis on China Mobile Network Communication Group, monitored client’s risk exposures and incorporated measurements such as retention rate and management team stability to indicate client’s financial
stability.

- Complied with analytical reports on assigned decks and presented for senior leadership, focused on the deck’s investment in communication infrastructure domestically and globally. 

**Bank of Communications Financial Leasing Co., Ltd: Intern, Business Development May- Aug 2020 Shanghai, CN**

- Used Wind and Polaris Power Grid for supply and demand analysis on the Electric Power industry; focused on the division of capital in the primary and secondary industries; edited the Industrial Risk and Strategy section of Industry White Paper 2019.

## Leadership experience
**QingPei Education (Tutoring Program for students in rural Guizhou): Co-founder Aug 2016-present, CN**

- Provide systematic tutoring for middle/high school students in rural Guizhou, serving 120+ students per year; collaborate with the local Bureau of Health to carry out free physical exam program and counseling service.

**Student Union of Sichuan University: Chair, Depart of Culture and Art Oct 2016-2020 Chengdu, CN**

- Led an initiative to help families affected by COVID-19; coordinated distribution of daily supplies to 500 families in quarantine; founded a mental health program to help students affected by the pandemic recover from PTSD.
- Founded “Wing of the Phoenix” series - a leading on-campus cultural activity with debate, choir, dance, and singing events. Managed organization and execution, attracting 800 vendors and 4,000+ attendees.
